---
driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35
  max_retries: 3
  wait_for_retry: 90
  client_rb:
    exit_status: :enabled
    client_fork: false

platforms:
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[win_ad::default]
    attributes:

