name 'win_ad'
maintainer 'John Snow'
maintainer_email 'jsnow@chef.io'
license 'Apache-2.0'
description 'Installs/Configures win_ad'
long_description 'Installs/Configures win_ad'
version '3.0.6'
supports 'windows'
