name 'win_ad'
maintainer 'John Snow'
maintainer_email 'jsnow@chef.io'
license 'Apache-2.0'
description 'Resources for interacting with Active Directory'
long_description 'Installs/Configures win_ad'
version '3.0.7'
supports 'windows'
depends 'windows'
source_url 'https://github.com/TheLunaticScripter/win_ad9'
issues_url 'https://github.com/TheLunaticScripter/win_ad/issues'
chef_version '>= 12.7' if respond_to?(:chef_version)
